### ISSUE TITLE
White Dwarf example.  

### ISSUE THREAD

**Issue by michaelJwilson** [michaelJwilson/DESI-HighSchool#4]
@cylammarco  I've added the start of a notebook under sandbox/ with the spectral data and propagated targeting (e.g. GAIA).     There may be standards info. available for this, e.g. surface gravity, but I haven't found it yet - I may need to cross with some other pipeline files.  If we can derive it independently (easily) then let's do that.  Thanks for tagging along on us!

**Comment by michaelJwilson** [comment]
@cylammarco This was a really useful start! 

I jazzed up the back story.  I didn't spend long checking up on my stellar history, so please point out where I've taken some liberties with the truth. 

Do I have it right, in that your use of 'spectroscopic distance' relies on a few standards of known distance from parallax that calibrate the intrinsic luminosity of a WD spectrum of given shape?  Is mbol_da apparent bolometric magnitude, as implied?  I take it the parameters of the grid are then not independent.  The rest makes sense to me if so.  I'll take a stab at making the second half more accessible tomorrow. 

Ideally, rather than the spec. distance [which appears pretty discrepant ;) ], we'd spin the end as implication of fitted temperature and surface gravity on the intrinsic properties given known distance, e.g. radius.  Is this possible?

Remaining hooks to be built in: 
- Degeneracy pressure and QM.
- Tye in to Type-Ia supernovae introduced in the Intro (and Dark Energy by extension).
- Other?

**Comment by michaelJwilson** [comment]
Oh, and what is DA(!)

**Comment by cylammarco** [comment]
> _Do I have it right, in that your use of 'spectroscopic distance' relies on a few standards of known distance from parallax that calibrate the intrinsic luminosity of a WD spectrum of given shape?_

Yes, the same concept as standard candles, once we have a few standards at accurately known distances and high quality spectra collected, we can iterate through different moving groups/clusters (where all stars are essentially all at the same distance) and then apply the distance to other stars that are not available in the immediate solar neighbourhood.

> _Is mbol_da apparent bolometric magnitude, as implied? I take it the parameters of the grid are then not independent._

That's the absolute bolometric magnitude, all at 10pc. Hence, there are a few `dist_mod` throughout, which is the distance modulus to convert between absolute and apparent.

> _Ideally, rather than the spec. distance [which appears pretty discrepant ;) ], we'd spin the end as implication of fitted temperature and surface gravity on the intrinsic properties given known distance, e.g. radius. Is this possible?_

All these (basic) models have assumed a mass-radius relation, so we can't really fit for the radius. We can only play with these three parameters: {Temperature, Gravity, Distance}. However, we can get the cooling time (i.e. post-main sequence age, time since it "exploded") based on the temperature and gravity. We can al

> _Remaining hooks to be built in:_
> - _Degeneracy pressure and QM._
> - _Motivate the models_
> - _Tie into Type-Ia supernovae introduced in the Intro (and Dark Energy by extension)._

- Maybe we can link the degeneracy pressure (seems rather difficult to deliver at high-school level) and the mass-radius relation. As WD mass increases, the radius decreases, at the point when gravity beats the degeneracy pressure, it collapses. 
- We can also touch the surface of asteroseismology that their pulsation patterns (if there is) let us understand the stellar interior.
- WD has the MK spectral type `D`. The second letter denotes the atmospheric properties (chemistry + physical properties that are applicable), `A` is hydrogen, `B` is helium... see [here](https://iopscience.iop.org/article/10.3847/2515-5172/ab3469) for the complete listing.

**Comment by michaelJwilson** [comment]
> Yes, the same concept as standard candles, once we have a few standards at accurately known distances and high quality spectra collected, we can iterate through different moving groups/clusters (where all stars are essentially all at the same distance) and then apply the distance to other stars that are not available in the immediate solar neighbourhood.
Ok, irrespective of the nearest neighbor propagation from clusters, it's still calibrating the spectrum to luminosity relation.  Sounds good. 

> That's the absolute bolometric magnitude, all at 10pc.
Let's go with Mbol_da :) 

> We can only play with these three parameters: {Temperature, Gravity, Distance}. However, we can get the cooling time (i.e. post-main sequence age, time since it "exploded") based on the temperature and gravity.
There's just an angle missing on what we learn from the fitted parameters.  Maybe just discussing the temperature and surface gravity is enough, but being able to motivate more would be great.  Cooling time sounds like a great start.

>  Maybe we can link the degeneracy pressure (seems rather difficult to deliver at high-school level) 
Agreed.  We aren't going to explain QM, but the idea that the star is only stable due to quantum mechanics is a neat one and we should touch on it at least.  

> pulsation patterns
Are these Gaia (with correct capitalization!) derived, or independently?  

> WD has the MK spectral type D
Seems like this is Type-1a related?  I'm not getting the connection.  

Almost there.  Thanks!

**Comment by michaelJwilson** [comment]
Ok, seems we're done here, thanks for the help!  Let's reopen if anything is awry.  It's also covered by travis now.
